name = "sugo"
main = "worker.js"
compatibility_date = "2026-07-11"
workers_dev = true
preview_urls = false

[[kv_namespaces]]
binding = "SUGO_KV"
id = "3b5051a5b7b143afa1f4522afa0c53d4"

[vars]
DEBUG_ERRORS = "false"
STRICT_ACCURACY_GATE = "true"
